### PR TITLE
Support reading utf8+utf16 with BOM

### LINKED ISSUE #142: Incorrect bean property
Hello,

I'm trying to read a CSV file with the header but seems that name of the set method has an character in lowercase:
org.supercsv.exception.SuperCsvReflectionException: unable to find method **set﻿idOrder**(java.lang.Integer) 

The name of the bean property is idOrder and the Header is idOrder so the set name of the method should be setIdOrder.

Any suggestion?

Thank you for your support,
Raffaele Latela

[201805081341477_ORDERS.csv.zip](https://github.com/super-csv/super-csv/files/1984424/201805081341477_ORDERS.csv.zip)

### PR DESCRIPTION
**Pull request by dota17**
Fix #142

### CODE REVIEW

**Comment by dota17** [comment]
Hi, @kbilsted 
Thank you for your advice. I'll refactor this code.

**Comment by dota17** [comment]
Hi, @kbilsted 
After trying, only ```"\uFEFF"``` BOM information is left in Java, no matter the file is utf8 with BOM, utf16le, utf16be. Therefore, it only need to deal with the situation of ```"\uFEFF"```

**Comment by kbilsted** [comment]
@dota17  many thanks for your input. it is really strange since my understanding of the BOM's correspond to https://en.wikipedia.org/wiki/Byte_order_mark

**Comment by dota17** [comment]
Hi, @kbilsted 
I agree, the BOM in the following is the same as you understand. However, after the code reading is processed through the Java read API, ```"\ufeff"``` will be left in Java at the first of the string. Because the Java read API only converts the files with different encoding into the unified Java Unicode code, but does not remove the BOM.
```java
BufferedReader reader = new BufferedReader(new InputStreamReader(
                                                  new FileInputStream(UTF8_FILE), "UTF-8"));
BufferedReader reader = new BufferedReader(new InputStreamReader(
                                                  new FileInputStream(UTF16BE_FILE), "UTF-16"));
BufferedReader reader = new BufferedReader(new InputStreamReader(
                                                  new FileInputStream(UTF16LE_FILE), "UTF-18"));
```
customers_utf8.csv:
image
customers_utf16be.csv:
image
customers_utf16le.csv:
image

**Comment by dota17** [comment]
Hi, @kbilsted 
What about this PR? Close?

**Comment by kbilsted** [comment]
nice detail you only try to subtract on the first line

**Comment by dota17** [comment]
Hi, @kbilsted 
I will submit the PR of release note immediately (#184 ).  Release note for v2.50 about supporting UTF8 or UTF16 will be included in that PR.

**Comment by kbilsted** [comment]
great stuff!

**Comment by kbilsted** [comment]
@dota17  do you know rebasing in git? it creates cleaner history than merging master

**Comment by dota17** [comment]
Hi, @kbilsted 
I know rebasing in git. I'll pay attention next time. Thank you!

**Comment by kbilsted** [comment]
@dota17 no worries ;-)

**Pull request merged**
