### PR TITLE
Declarative extension

### PR DESCRIPTION
**Pull request by dkschlos**
This extension allows declarative bean to/from csv mappings via annotations.
The new classes CsvDeclarativeBeanReader and CsvDeclarativeBeanWriter don't accept name-mappings or CellProcessor-lists but instead use conventions and new annotations to create CellProcessor-pipelines and map csv-files to beans and vice versa:

```java
@Trim
@Truncate(maxSize = 3)
private String lastName;
```
is transformed autmatically into new Trim(new Truncate()).
If no relevant annotations can be found for a field, the writer/reader automatically adds processors via convention if appropriate (for example ParseBool() for boolean fields when reading).

Still missing:
* Documentation (gh-pages and javadoc is incomplete)
* Tests (including performance tests in super-csv-benchmark; basic tests exist, though!)

### CODE REVIEW

**Comment by dkschlos** [comment]
I know, this is quite a big extension without any warning ;-) It was a rather spontaneous idea at work after I got frustrated by the rather verbose and redundant configuration of vanilla super-csv.

I am going to close this PR and I have already opened a standalone repo for this extension:
https://github.com/dkschlos/super-csv-declarative which also has a little more documentation especially regarding problems with field/annotation-order when using reflection.

Just get in touch if you would like to merge this extension to the main project.

**Comment by kbilsted** [comment]
Hi @dkschlos 

Thanks for the PR... which now is no longer..:-)

We have had a discussion on annotations earlier in time..in some other issue..https://github.com/super-csv/super-csv/issues/35 but generally  . I'm mostly concerned with this approach when you are using custom processors not part of the official distribution. Also there may be a problem with passing parameters and keeping compile-time safety when multiple annotations are applied to one field.

We have subprojects for supercsv as well, so maybe we can do something about putting the repo within the supercsv organization or something.

**Comment by kbilsted** [comment]
reopening issue untill we have a good solution..

**Comment by dkschlos** [comment]
I will open a new PR with a single commit and with fixed line endings.

**Comment by dkschlos** [comment]
Opened #105

**Pull request closed without merging**
