### PR TITLE
add CSV preference for writing a header

### PR DESCRIPTION
**Pull request by ChristianWilkie**
see #149 

not sure if this is the best way to do it or not since I'm not sure if this preference affects writers other than CsvResultSetWriter , and I also had to expose the encapsulated CsvPreference object to access it within CsvResultSetWriter to determine whether or not to write the header

let me know what you think and I can change things, thank you for taking the time to review!

### CODE REVIEW

**Comment by kbilsted** [comment]
Hi @ChristianWilkie  In the previous PR I was just asking if the preferences was a better place, But I think as you observe here and looking at the code, that perhaps the preferences is for general configuration not for particular writers. E.g. what happens if writeheader is false and you call writeheader() manually (in the other writers that have explicit methods for header writing).

@jjenkov @dota17

**Comment by ChristianWilkie** [comment]
Yeah I wasn't sure myself either, just were my thoughts when I was writing it.. I think it would make more sense just for the ResultWriter - since that class uniquely seems to write the headers automatically



With the BeanWriter for instance you have to manually call writeHeader yourself. The write method doesn't call writeHeader: https://github.com/super-csv/super-csv/blob/f18db724674dc1c4116e25142c1b5403ebf43e96/super-csv/src/main/java/org/supercsv/io/CsvBeanWriter.java#L111-L121


but with the ResultSetWriter acts differently and implictly calls writeHeader through the write method:

https://github.com/super-csv/super-csv/blob/f18db724674dc1c4116e25142c1b5403ebf43e96/super-csv/src/main/java/org/supercsv/io/CsvResultSetWriter.java#L70-L80

So would it make more sense to close/reject this PR and instead we could add it as an option to the ResultSetWriter, maybe a constructor option to change this implicit behavior? thoughts?

The other PR I made works like that by adding a boolean parameter with another constructor (#149): https://github.com/super-csv/super-csv/pull/149/commits/1a8f4290719123c0afdc85cec24173473f9362fe

**Comment by dota17** [comment]
Hi, @kbilsted , @ChristianWilkie 
I don't think PR #171  is a good implementation. And I think ```CsvPreference``` should not be associated with ```writeheader```.  I prefer the implementation which devide ```write``` into  ```writeHeader``` API and ```write``` API like other ```CsvWriter```.

**Comment by kbilsted** [comment]
We agree that #149 is a better approach. I'm Sorry you wasted time implementing, I thought we could just discuss pros/cons ;)

**Pull request closed without merging**
