### PR TITLE
issue #13 - Preference to distinguish between null and empty columns

### PR DESCRIPTION
**Pull request by pietroaragona**
I implemented this issue. I hope it's ok.

### CODE REVIEW

**Comment by kbilsted** [comment]
@ZioberMichal  and @singularityfx  any comments?

**Comment by ZioberMichal** [comment]
1. Sorry, I thought I had commented this PR before. After all changes this PR looks really good.
2. If this feature is really needed to someone we can release new minor version earlier.
3. At the end, @pietroaragona could you please merge these 3 commits into one? It would be much easier to find in future when this feature was made and see all changes related with it.

**Comment by kbilsted** [comment]
Just  git rebase -i head~3

**Comment by pietroaragona** [comment]
@kbilsted I have some problem to rebase... can I create a new branch with only one commit  and then a new PR to replace this one?

**Comment by kbilsted** [comment]
You just need to force push after the rebase
Den 18/12/2015 17.10 skrev "Pietro Aragona" <notifications@github.com>:

**Comment by pietroaragona** [comment]
Thank you for suggestions, I did rebase succesfully  when I added ParseTime processor, but this time I have a problem with command rebase:

```
git rebase --interactive HEAD~3
error: could not apply e3e45dc... issue #13 - Preference to distinguish between null and empty columns

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

Could not apply e3e45dcd84deb5cfb6f178854f996ab39ef19f7a... issue #13 - Preference to distinguish between null and empty columns
```

I don't know how to resolve it then I think that I will create a new PR...

**Comment by kbilsted** [comment]
Run gitk or other gui tool and resolve.  Not sure I understand why there is
a conflict.  Did you fix or squash or move commits around?
Den 19/12/2015 21.41 skrev "Pietro Aragona" <notifications@github.com>:

**Comment by pietroaragona** [comment]
I'd  squash commits. I'm trying to resolve with gitk

**Comment by kbilsted** [comment]
Not sure why there would be any conflicts then
Den 19/12/2015 22.20 skrev "Pietro Aragona" <notifications@github.com>:

**Comment by pietroaragona** [comment]
Thank you @kbilsted , now there is only one commit ;-)

**Comment by ZioberMichal** [comment]
Good job, now it looks much clear.

**Pull request merged**
