### PR TITLE
Documentation for null vs empty column parsing preference

### PR DESCRIPTION
**Pull request by ash211**
Fixes https://github.com/super-csv/super-csv/issues/102

### CODE REVIEW

**Comment by ash211** [comment]
@kbilsted are you able to review this PR this week?  It's the last issue blocking the next release

**Comment by kbilsted** [comment]
Sorry was in Italy getting drunk all week last week :-p  .. recovering

**Comment by ash211** [comment]
Haha!  One week of wine => one week of recovery..  I'll not expect anything from you until next week then!  Hope you had a wonderful time.

**Comment by ash211** [comment]
@kbilsted any chance we could get this in and cut a release this week or next?  Hopefully you have now recovered! haha

**Comment by kbilsted** [comment]
@ash211  sorry. So busy with other stuff. In the past I've asked people if they want to take over the project and I only sit (idle!) on the side line. Work has been done, but people seems to have run out of steam.

**Comment by ash211** [comment]
Understood, this is obviously not a full-time job for any of us.  I appreciate the work you do for this project!

Is there anything I can do to help with the release now?  What's the process for that look like?

**Comment by kbilsted** [comment]
hi @ash211 

We use maven for releases. do you have any experience with maven? Would you be interested in being the release manager?

**Comment by ash211** [comment]
I'm much more familiar with gradle than maven, but I think I can figure it out.  Happy to serve as the release manager for this release!

What permissions would I need for that?  Are there any docs left for us by past release managers?

**Comment by kbilsted** [comment]
I think someone permanent would be better due to security tokens etc.

**Comment by kbilsted** [comment]
@ZioberMichal  did the last release. Maybe we can persuade him to do one more? ;-)

**Comment by kbilsted** [comment]
and to be honest I haven't setup my machine to do releases since for a couple of years now I'm only on the side line of the project - and I kind of want it that way since I rarely code in Java.

**Comment by ZioberMichal** [comment]
@kbilsted , @ash211, I had really tough times in recent months... But I ma back :) I need about one week and I am ready to release new version. I need to checkout all new changes and see what happened in meantime when I was far away this project.

**Comment by ash211** [comment]
@ZioberMichal sorry to hear that!  I hope you're doing well again.

Do you have any questions about recent changes?

**Comment by kbilsted** [comment]
@ziobermichal  are you ok now? Hope you are well.

**Comment by ZioberMichal** [comment]
@ash211, @kbilsted - thank you for asking. Yes, I am OK. I did not have time for github because I bought a flat and I had to finish it, so you see ...  I had another kind of work 😃 

I will try to check all pull requests and try to merge them. After that we have to test the result and if everything will be OK, we can release new version.

**Comment by kbilsted** [comment]
@ZioberMichal  glad to hear :) congratulations with the new apartment. Don't feel bad about being away from the project.. its all about doing things when you have the energy for it :)

**Comment by kbilsted** [comment]
@ZioberMichal  all PRs are merged to master and issues are created for each PR as far as I remember

**Comment by ZioberMichal** [comment]
@kbilsted, I see. I thought that we also want to merge other PR-es which are still not merged.

**Comment by kbilsted** [comment]
@ZioberMichal  that is a good point. Some of them have been laying dormant for some time. I think for the most cases the following things have not been considered

  * a better java 8 version possible?
  * documentation
  * unittests
  * formatting of the code

**Pull request merged**
