### PR TITLE
ParseTime

### PR DESCRIPTION
**Pull request by pietroaragona**
Hi,
I implemented the new ParseTime to convert String to Time Objects.
I created an abstract class (ParseDateTimeAbstract) extended  by ParseDate and ParseTime.
I modified also JUnit test adding the birthTime to PersonBean.

Pietro

### CODE REVIEW

**Comment by kbilsted** [comment]
what do you think @singularityfx @ZioberMichal   ? I think it looks fine..

**Comment by ZioberMichal** [comment]
@pietroaragona, well done. For me it also looks good.

**Comment by kbilsted** [comment]
Looks good, but I think ParseTime is difficult to understand given the many time-classes out there. Isn't a better `ParseSqlTime` ?`what do you think @pietroaragona  @ZioberMichal

**Comment by ZioberMichal** [comment]
`ParseSqlTime` sounds reasonable but if we change this we should probably rename `FmtTime` to `FmtSqlTime` as well.

**Comment by kbilsted** [comment]
@ZioberMichal  good point

**Comment by pietroaragona** [comment]
@kbilsted @ZioberMichal  yes, ParseSqlTime and FmtSqlTime are more clear.

**Comment by pietroaragona** [comment]
@kbilsted @ZioberMichal I pushed the changes.

**Comment by ZioberMichal** [comment]
Great, looks good. Could you also merge your commits into one commit?

**Comment by pietroaragona** [comment]
@ZioberMichal let me know if it's ok now

**Comment by kbilsted** [comment]
Thanks a bunch @pietroaragona

**Pull request merged**
