### PR TITLE
Implemented new CellProcessor in order to convert Date in Time Object

### PR DESCRIPTION
**Pull request by pietroaragona**
Hi,
I created this new CellProcessor because I need read a value from csv file in a bean' s field of type java.sql.Time.

I hope this can be useful to others.

Pietro

### CODE REVIEW

**Comment by kbilsted** [comment]
Great many thanks! I cannot help but wonder if it was more natural if the processor would handle strings as well as Date ? It will also make it easier for users to use as they do not need to wrap it into another processor.. I guess both types could be accepted. What are your oppinions @dmitry87 @ZioberMichal

**Comment by dmitry87** [comment]
Yep, it would be better if it handled Strings too. At least other Processors try.

**Comment by pietroaragona** [comment]
Ok,  I will do it in this week

Il giorno mar 6 ott 2015 18:29 dmitry87 <notifications@github.com> ha
scritto:

**Comment by ZioberMichal** [comment]
It is a good idea to add `String`. You can check how `FmtDate` class it is implemented.

**Comment by pietroaragona** [comment]
I' m thinking to change ParseTime as sub class of ParseDate (public class
ParseTime extends ParseDate { )
because the execute method will be the same (Only the effective return type
will not )

than I will create a FmtTime as suggested by Michael and I will add a field
to PersonBean of type Time (maybe birthTime?) to complete the example with
the new Processor.

It's ok for you?


2015-10-07 16:45 GMT+02:00 Michał Ziober <notifications@github.com>:

> It is a good idea to add String. You can check how FmtDate class it is
> implemented.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/super-csv/super-csv/pull/74#issuecomment-146216830>.
>



-- 
Pietro Aragona

**Comment by kbilsted** [comment]
I don't think we should use inheritance for code reuse  like this. Then it's better to create an abstract class that both ParseDate  and ParseTime can inherit from. This is cleaner and more reusable.

**Comment by kbilsted** [comment]
@pietroaragona  sorry for the long wait. I want to merge in these changes. All we need in this PR is to update the documentation pages.

**Pull request closed without merging**
