### PR TITLE
Merge remote-tracking branch 'origin/DDV_BRANCH_1'

### PR DESCRIPTION
**Pull request by kbilsted**
All changes made by DDV have already been cherry picked into the master branch. Just cleaning up here.

 Please make it an explicit merge rather than a rebase. We want his name as the contributor, and we want an empty merge.

### CODE REVIEW

**Comment by jamesbassett** [comment]
Sorry I'm confused what's happening here...why are we merging? 

I thought we should be deleting this branch (as you've said, all the changes are in master), not merging it!

And Dominique isn't listed as a contributor because I couldn't find him on GitHub (the only email I could find from svn was ddv36a78@yahoo.fr), so he has no email associated with his commits to master. Looks like there's some [rules](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/) for how that works as well.

If he's on GitHub (are you in contact with him??), we could update his commits to include his GitHub email, and that should make him listed as a contributor.

**Comment by kbilsted** [comment]
Good question. I like the PR model since it gives us a chance to discuss before push.

1. I like to retain the history since Dominic's changes are only to be found in the graph on that branch.
2. It retains history - despite him not being on github
3. when working with Hg and Git branches are light weight and not to be feared. At work we have a lot of branches, which isn't a problem
4. Tracing DDV could be fun in a way, let me see if google gives us anything

**Comment by jamesbassett** [comment]
Sorry I'm a bit slow to understand! So the whole reason you're doing this is to split your single [Merged Dominicque's changes](https://github.com/super-csv/super-csv/commit/6a10644348a4f655773a8630c2fd058502b3e417) commit into the separate commits DDV made on his branch? 

Like I said, I would have just deleted the branch (all his changes are in master, and he's got credit in the commit message), but if you want to do it that's cool.  I guess I'm just hesitant to rewrite history now that people have started forking/cloning. My 'apply mail' merge broke with this PR, so I'll let you hit the merge pull request button if you want this :)

**Comment by kbilsted** [comment]
But there are no commits with his name on in the history if we nuke the branch. Also, we are doing so many commits, that this merge node will soon disappear from the top most of the graph :)

**Comment by jamesbassett** [comment]
There were commits by DDV already there, just not the ones on that branch. 

If you do get in touch with him and he has a GitHub account, then he can just [add](https://help.github.com/articles/adding-an-email-address-to-your-github-account/) ddv36a78@users.sf.net to his GitHub account and it should link it to him :)

**Comment by jamesbassett** [comment]
Bah, this merge overwrote the tidy up I did when merging your Tokenizer change - glad I didn't have any other changes!

**Comment by kbilsted** [comment]
just do an explicit merge rather than always rebasing. In Hg, at least, rebasing over a merge node can be problematic depending on how you do it..

**Pull request merged**
