### PR TITLE
Turkey test fix

### PR DESCRIPTION
**Pull request by ZioberMichal**
Replaced all String’s methods `toUpperCase()` to
`toUpperCase(Locale.ENGLISH)`.
Added turkishLocale profile to check whether app passes “Turkey test”.

#16

### CODE REVIEW

**Comment by kbilsted** [comment]
rather than hardcoding the locale, should it be part of the CsvPreference-class?

**Comment by ZioberMichal** [comment]
In this case, ENGLISH locale prevents from consequences of using default (system) locales. This is a part of algorithm "how to properly do upper case". If we extract it to configuration maybe some users who do not know what it really means will set it to Turkish locales.

This change does not solve the problem because like I wrote in previous post `equalsIgnoreCase` solves problem. We can revert this change and everything will be OK. By this change I wanted explicitly  say - "convert it without worrying about local characters".

Please, let me know what do you think about it and how it should be solved properly.

**Comment by kbilsted** [comment]
would you mind combining these using  `git reset --soft head~3` ? I dont min small commits but these ones are going backwards and forward changing the same lines :) Also we should add a comment on the `equalsIgnoreCase()` telling its important to ignore the casing for a number of reasons, one being the turkey-issue

**Comment by ZioberMichal** [comment]
Actually I combined these 3 commits into one using your tip(thanks for it!) but I do not know how to override my PR. I've never done this before...

**Comment by ZioberMichal** [comment]
I have found an answer - just add force flag helped ;)

**Pull request merged**
