### PR TITLE
Test: Fixing locale issue

### LINKED ISSUE #18: Unit test is locale dependent
A test is locale dependent, and hence fail in Denmark

### PR DESCRIPTION
**Pull request by kbilsted**
Closes #18

### CODE REVIEW

**Comment by jamesbassett** [comment]
I haven't looked at the memory usage commit yet, so reopening this PR.

**Comment by kbilsted** [comment]
Look at p.r. 21 instead.  It has the changes  isolated..

**Comment by jamesbassett** [comment]
Ah sweet, thanks.

**Comment by kbilsted** [comment]
Yeah, I had to do some branch gymnastics in order to do multiple independent PR's. Git is a bit different than Hg in that respect. I'm pretty good with Hg and less skilled at Git. So it was fun to play around with branches, cherry picking, and upstream fetching etc. etc.

**Pull request closed without merging**
