### PR TITLE
Add JDBC ResultSet writer. Closes #6

### LINKED ISSUE #6: JDBC ResultSet writer
A writer to write a JDBC ResultSet as CSV.

Originally raised as Feature Request 38 on [SourceForge](http://sourceforge.net/p/supercsv/feature-requests/38/)

### PR DESCRIPTION
**Pull request by singularityfx**
Add a writer to write a JDBC ResultSet as CSV.

CsvResultSetWriter writes a CSV file by mapping each column of the
ResultSet to a column in CSV file using column names stored in
ResultSetMetaData. It can be used with or without CellProcessors.

Closes issue #6.

### CODE REVIEW

**Comment by kbilsted** [comment]
Great stuff. I'm swamped at work at the moment will need to look into this later than I want to.

**Comment by singularityfx** [comment]
Hi Kasper! Thanks for feedback! 

>  how about filling the array with null's instead

Agreed.

>  why do you need so many rows, what important data differ in each of them?
>  could/should the test data be extracted into a separate class and reused in other tests?

This is the same test data that is used in CsvBeanWriterTest & CsvBeanReaderTest. There are CustomerBean objects in org.supercsv.SuperCsvTestUtils which are constructed with the same values that I have in my arrays.

Perhaps it is better to:
1. move these arrays to SuperCsvTestUtils
2. create CustomerBeans from array elements

In fact I don’t think that we need that much rows, but keeping it that way allows to reuse the CSV output contained in SuperCsvTestUtils.CSV_FILE.

**Comment by kbilsted** [comment]
Hi @singularityfx  I was of the impression you wanted to work further with this? Or do you believe you are done?

**Comment by singularityfx** [comment]
@kbilsted Yes, I want to work further with this, just let's agree on what shall be done:
 - pass array of nulls? Or get rid of dummyProcessors at all?
 - refactor the tests as described in my message above?
 - anything else?

**Comment by kbilsted** [comment]
Hi thanks for getting back.

Try out James idea or if failing use nulls. The other refactoring of the tests sounds good.

**Comment by singularityfx** [comment]
@kbilsted @jamesbassett Done

**Comment by kbilsted** [comment]
Great stuff @singularityfx  ! Thanks!  @jamesbassett  did you have anything to add?

**Comment by jamesbassett** [comment]
Yep, I'm at work right now, but here's some feedback (sorry for taking so long) :)

* Revert the changes to `SuperCsvTestUtils`, and instead set up the test data in your `CsvResultSetWriterTest`. Instead of duplicating the data, create a utility method that takes the List of `CustomerBean`s from `SuperCsvTestUtils` (i.e. `SuperCsvTestUtils.CUSTOMERS`) and creates your result set test data (array of arrays) from it.

Documentation (you can test this with `mvn site:run`):
* Add the new writer to super-csv/src/site/apt/writers.apt
* Add a `writeWithResultSetWriter()` method to super-csv/super-csv/src/test/java/org/supercsv/example/Writing.java
* Create a new super-csv/src/site/apt/examples_jdbc.apt page with an example of how to use it (use the code/output from the previous step, as is done for all the other readers/writers).
* Add your page to the site index (super-csv/src/site/site.xml) after the dozer example

Coding standards:
* add `final` modifier to all method params and variables
* remove `public` modifier from all interface methods (it's implicit)
* change copyright to Kasper

**Comment by singularityfx** [comment]
@jamesbassett Thanks for feedback! Regarding the first point. I was considering this option, but it would made the test less isolated by introducing dependency on `CustomerBean` class. Are you sure you want this? Also having the test data in arrays inside `SuperCsvTestUtils` will make it easier to reuse the data in future. Please let me know what do you think.

**Comment by jamesbassett** [comment]
Yeah ok.  How about adding the following to SuperCsvTestUtils:

public static final ResultSet CUSTOMER_RESULT_SET =
createCustomerResultSet();
public static final ResultSet STRING_CUSTOMER_RESULT_SET =
createStringCustomerResultSet();

private static ResultSet createCustomerResultSet(){
    // TODO create ResultSet from CUSTOMERS
}

private static ResultSet createStringCustomerResultSet(){
    // TODO create ResultSet from STRING_CUSTOMERS
}

**Comment by singularityfx** [comment]
> Yeah ok. How about adding the following to SuperCsvTestUtils

I didn't want to extract the data from CustomerBeans because then my test will depend on CustomerBean class - if someone make changes to CustomerBean, then my test may break, while it has nothing to do with CustomerBeans. But if you insist I can do that, no problem. Just for my understanding - what is the benefit of this approach?

**Comment by jamesbassett** [comment]
I wasn't keen on having the test data array and all the casts and array indices it required.  I get where you're coming from regarding keeping things isolated, but in this case I think the CustomerBeans are the best place for the test data to be defined (you get type safe constructor params, and the data is visible beside the CustomerBean definition). 

The fact that the result set test data is created in the very same class makes it easier to maintain, and should be obvious that any changes to the CustomerBeans will impact that as well (and will cause tests to fail).

So I'd prefer it to be done as suggested, though I'd make the new constants be `Object[][]` as you had initially - my comment about making them `ResultSet`s was a bit silly now that I think about it (they probably have state!).

**Comment by singularityfx** [comment]
@jamesbassett OK, I undestand your point now. I'll do as you suggested.

**Comment by singularityfx** [comment]
@kbilsted @jamesbassett OK, done

**Comment by kbilsted** [comment]
Many thanks for your persistence!

**Comment by kbilsted** [comment]
Sorry I still haven't looked at it. Maternity leave is starting monday! Should provide me with time :-)

**Comment by singularityfx** [comment]
Great! Hope it will be useful.
Do I qualify for being included to the list of contributors?  (http://super-csv.github.io/super-csv/team-list.html) It would give me a warm and fuzzy feeling :)

**Comment by kbilsted** [comment]
I have a hård time seeing why not. Have you seen my invite for the github supercsv team?

**Comment by kbilsted** [comment]
Make it a pull request..being added to the list:)

**Comment by singularityfx** [comment]
Hmm, it looks like there is no source for http://super-csv.github.io/super-csv/team-list.html in the repo

**Comment by kbilsted** [comment]
Look at the branch `gh-pages`

**Comment by jamesbassett** [comment]
It's generated with mvn:site (you just need to edit the pom.xml file and it will appear the next time we release).

**Comment by singularityfx** [comment]
Thanks for explanations!

**Pull request merged**
