### PR TITLE
Add custom field mapping to CsvBeanReader

### PR DESCRIPTION
**Pull request by vyacheslav-pushkin**
Add additional overloaded read() methods to CsvBeanReader that accepts
column name mappings and cell processors as maps instead of arrays.
The new methods:
- allows to read beans directly from CSV when CSV headers are different than
  bean field names
- has no dependency on columns number or order
- are more convenient in case of CSV files with large number of columns

Closes issue #65

### CODE REVIEW

**Comment by ZioberMichal** [comment]
Hi @singularityfx, nice PR with good implementation. :+1: 

Now, I am thinking on "client side" and how this feature can be used by someone. Currently we have two `Map`s as parameters where keys are the same (have the same meaning - column name) only values are different. Using these two maps - you links three different objects. I think it is a little inconvenient and "error prone".

What do you think about new type which contains all these values? For example:
```java
public class CsvColumn {
    private final String columnName;
    private final String propertyName;
    private final CellProcessor processor;

    // getters, constructors, toString, etc.

    public static CsvColumn of(...) {
       return new CsvColumn(...);
    }
}
```

Now user can prepare data for this method in this way:
```java
....
columns.add(CsvColumn.of("First name", "name"));
columns.add(CsvColumn.of("Last name", "surname"));
columns.add(CsvColumn.of("date of birth", "birthDate", new ParseDate("dd/MM/yyyy"));
```

and finally read method could look like this:
```java
public <T> T read(final Class<T> clazz, final Collection<CsvColumn> columnsMapping)
```

I think that implementation of this feature will be much simpler and using of it by clients should be easier as well.

Of course `CsvColumn` it is just an example. We can find better name.

@singularityfx , @kbilsted  please let me know what do you think about this change.

**Comment by kbilsted** [comment]
I agree with Michal. It seems a worse approach than simply handle a dictionary field by field with code. It is more type-safe and supports nested objects. 

An alternative to yours and Michal that I want to bring into the discussion is simply with the read method that you can supply a string that will be read as the header overriding the header if it exists. Alternatively it could be a string array but its a bit more clumsy to type but allows reuse across files with different separators. This approach I feel I much more terse and to the point

**Comment by ZioberMichal** [comment]
@singularityfx, what do you think about our propositions?

**Comment by singularityfx** [comment]
@kbilsted @ZioberMichal Sorry for not answering earlier, I'm quite busy these days.

Your proposals are great! I would prefer Michal's approach, because the idea was not only to support custom name mappings but also allow to work easier with files that has lots of columns (i.e. avoid giant arrays with lots of nulls).

**Comment by singularityfx** [comment]
@kbilsted @ZioberMichal 

How about replacing `Collection<CsvColumn>` with `Map<String, BeanField>`, where String is columnName and BeanField is like CsvColumn, but only contains fieldName and cellProcessor?

Because:
    - we don't want several elements of columnsMapping collection pointing to the same columnName
    - we may want to overwrite the mapping for some of the columns in existing columnMapping

Then the client code can be like this:

`columnsMapping.put("date of birth", BeanField.of("birthDate", new ParseDate("dd/MM/yyyy"));`
`read(MyBean.class, columnsMapping);`

**Comment by kbilsted** [comment]
@singularityfx  I agree.. like I said before, we need to have the same features/interface for reading as lists, beans, maps, etc. sorry for delaying this PR for so long :-/ but I think its important that the API is consistent with itself..

**Comment by singularityfx** [comment]
@kbilsted Sure, I'll do that. Though it may take some time, because currently I'm a bit overwhelmed...

**Comment by singularityfx** [comment]
@kbilsted @ZioberMichal I've added read(Map<String, CellProcessor> columnMapping) method to CsvListReader and CsvMapReader. Please let me know what you think.

Another commit containing documentation changes (readers.apt, examples, etc.) will follow later.

**Comment by singularityfx** [comment]
@kbilsted @ZioberMichal Updated site documentation and cleaned up the PR a bit:

 - Reverted whitespace-only changes
 - Combined all changes into a single commit

Starting from 30-Oct I will disappear for a while because I need to concentrate on my new work. Need to learn new things, so will not have much free evenings in coming weeks :) Would be great if you can give me your feedback on PR this/next week so that I can make update if needed.

I do plan to come back, because I really like this project, and you guys are great team to work with :)

**Comment by kbilsted** [comment]
@ZioberMichal  Any feedback on this?

**Comment by ZioberMichal** [comment]
Yes, I saw this PR but it is hard to understand all these changes in diff editor which we have in GitHub. I have found some places which are tricky to me and I need to download probably this PR and check it in IntelliJ or Eclipse. As we can see this code has a lot of places where generics are used and I have noticed something like this: `((BeanField)beanField)`. I do not understand this cast-ing. Looks like @singularityfx left us for some time and I do not know what to do with this. We can merge it(or create new branch and merge this PR to it) and we could try to rewrite it a little to make it more clear. Generics and cast-ing do not look well together at the first sight.

What do you think?

**Comment by email2vimalraj** [comment]
+1 for this feature.

This is nice to have. Let me know in any way I can help in contribution.

**Comment by kbilsted** [comment]
@email2vimalraj a good start is to resolve the merge conflicts

**Comment by email2vimalraj** [comment]
@kbilsted thanks for giving me a task. So I'm currently working on resolving conflicts.
One question to you: Are we using Java 8 compiler?

Question is because, in ReadingFeaturesTest.java, the test method testReturnsTypedBean() uses the [getTypeName()](https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/Type.html#getTypeName--) method which was introduced in Java 8. This has no backward compatibility.

Kindly clarify.

**Comment by kbilsted** [comment]
The answer is found ato the root folder ...look at the folder names https://github.com/super-csv/super-csv?files=1

**Comment by email2vimalraj** [comment]
I've sent an another PR with all the problems in this PR solved. I'm not able to use the same PR.

**Comment by Snickbrack** [comment]
Is this feature lost in the current Version of 2.4.0? I dont see any possibility to use custom header names in the code side...

**Pull request closed without merging**
