### PR TITLE
#43 Error message fixed. Bug fixed when additional line is skipped

### PR DESCRIPTION
**Pull request by dmitry87**
Fix for issue #43 
It is fixing error message for maxLinesPerRow > 1 - current line is counted now.
No more additional line reads when there is a human error with skipping character.

### CODE REVIEW

**Comment by alankehoe** [comment]
+1

**Comment by Danm72** [comment]
+2

**Comment by kbilsted** [comment]
@jamesbassett  Any comments? Otherwise I'll merge.

**Comment by nickbabcock** [comment]
Great catch on my mistake! I'm surprised this bug hasn't burned me yet in production :smile:

**Pull request merged**
