### PR TITLE
Fix ISSUE#160(Cobertura does not support java 1.8)

### LINKED ISSUE #160: Cobertura does not support java 1.8
The jar cobertura-maven-plugin does not support java 1.8 [#ISSUE21](https://github.com/mojohaus/cobertura-maven-plugin/issues/21), which caused super-csv-java8 project can not to get test  case coverage report. So is it necessary to use other tool(e.g jacoco) instead of cobertura?

### PR DESCRIPTION
**Pull request by dota17**
Fix #160 
Using Jacobo instead of cobertura to support java8

### CODE REVIEW

**Comment by dota17** [comment]
Hi, @kbilsted 
So sorry! When using cobertura previously, the coverage report was in /target/site/cobertura/ index.html for each project, and now in /target/site/jacoco./index.htnl. You can use the command ```mvn test``` or ```mvn clean site```

**Comment by dota17** [comment]
Hi, @kbilsted 
Yeah, I know. I'll change the coverage report on the website

**Comment by dota17** [comment]
image

**Comment by kbilsted** [comment]
@dota17  great!
Is there a way to integrate it with github so it'll show the coverage directly in the PR - other code coverage tools has such an integration.

**Comment by dota17** [comment]
Hi, @kbilsted 
As shown in the picture, I successfully integrated test coverage through coveralls-maven-plugin and https://coveralls.io/ setting in [data17/super-csv repository](https://github.com/dota17/super-csv/pull/2) . But I don't know why it doesn't work in there. Travils CI build success and https://coveralls.io/ has partial data. Maybe it's about organization access.
image

**Pull request merged**
