### PR TITLE
#56 - test suite for Tokenizer read/write operations.

### PR DESCRIPTION
**Pull request by ZioberMichal**
1. Added two new tests which explicitly checks features from
http://csveed.org/comparison-matrix.html page (Tokenizer section).

### CODE REVIEW

**Comment by kbilsted** [comment]
Great stuff

**Comment by kbilsted** [comment]
Great stuff

**Comment by jamesbassett** [comment]
Looks good. Should we just call them `ReadingFeaturesTest` and `WritingFeaturesTest`? (Tokenizer is only relevant for reading).

**Comment by kbilsted** [comment]
Good idea
Den 11/07/2015 10.00 skrev "James Bassett" <notifications@github.com>:

**Comment by ZioberMichal** [comment]
Good point. Done!

**Comment by ZioberMichal** [comment]
I've implemented tests for each point from comparison page. Have you reviewed them? Should I fix something or change? Any advice is welcomed.

**Comment by ZioberMichal** [comment]
I've merged three last commits into one to make all these changes much clear.

**Comment by kbilsted** [comment]
Will have a look within Monday unless James beats me :)

**Comment by jamesbassett** [comment]
Yeah not likely, I'm super busy at work right now. So go for it :)

**Comment by ZioberMichal** [comment]
Hi guys, I want to recall that this PR is waiting for merging. Let me know if something should be fixed.

**Comment by kbilsted** [comment]
I'm sorry. The personal life & vacation has made it impossible for me to look at it any sooner.

**Comment by ZioberMichal** [comment]
No problem, it's understood :smile:

**Pull request merged**
